version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:8765"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.9
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - /var/mongodb-data:/data/db
